# Classifying Penguins with Keras

In [38]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn import preprocessing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve
import torch
from torch.utils.data import DataLoader, TensorDataset, random_split

In [39]:
! pip install palmerpenguins
from palmerpenguins import load_penguins
penguins = load_penguins()
penguins.head()

Requirement already satisfied: palmerpenguins in C:\Users\jfigg\.conda\envs\keras_env\Lib\site-packages (0.1.6)
Requirement already satisfied: pandas in C:\Users\jfigg\.conda\envs\keras_env\Lib\site-packages (from palmerpenguins) (2.1.4)
Requirement already satisfied: numpy in C:\Users\jfigg\.conda\envs\keras_env\Lib\site-packages (from palmerpenguins) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jfigg\.conda\envs\keras_env\Lib\site-packages (from pandas->palmerpenguins) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\jfigg\.conda\envs\keras_env\Lib\site-packages (from pandas->palmerpenguins) (2026.2)
Requirement already satisfied: tzdata>=2022.1 in C:\Users\jfigg\.conda\envs\keras_env\Lib\site-packages (from pandas->palmerpenguins) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\jfigg\.conda\envs\keras_env\Lib\site-packages (from python-dateutil>=2.8.2->pandas->palmerpenguins) (1.17.0)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [40]:
penguins = penguins.dropna().reset_index(drop=True)

In [41]:
penguins_x = pd.concat([penguins[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']], pd.get_dummies(penguins['sex'])], axis = 1)
# penguins_x = penguins_x[['body_mass_g', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'female', 'male']]
penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,3750.0,39.1,18.7,181.0,False,True
1,3800.0,39.5,17.4,186.0,True,False
2,3250.0,40.3,18.0,195.0,True,False
3,3450.0,36.7,19.3,193.0,True,False
4,3650.0,39.3,20.6,190.0,False,True
...,...,...,...,...,...,...
328,4000.0,55.8,19.8,207.0,False,True
329,3400.0,43.5,18.1,202.0,True,False
330,3775.0,49.6,18.2,193.0,False,True
331,4100.0,50.8,19.0,210.0,False,True
332,3775.0,50.2,18.7,198.0,True,False

In [42]:
x = penguins_x.values
min_max_scaler = preprocessing.MinMaxScaler()
scaled_penguins_x = pd.DataFrame(min_max_scaler.fit_transform(x), columns=penguins_x.columns)
scaled_penguins_x

,body_mass_g,bill_length_mm,bill_depth_mm,flipper_length_mm,female,male
0,0.291667,0.254545,0.666667,0.152542,0.0,1.0
1,0.305556,0.269091,0.511905,0.237288,1.0,0.0
2,0.152778,0.298182,0.583333,0.389831,1.0,0.0
3,0.208333,0.167273,0.738095,0.355932,1.0,0.0
4,0.263889,0.261818,0.892857,0.305085,0.0,1.0
...,...,...,...,...,...,...
328,0.361111,0.861818,0.797619,0.593220,0.0,1.0
329,0.194444,0.414545,0.595238,0.508475,1.0,0.0
330,0.298611,0.636364,0.607143,0.355932,0.0,1.0
331,0.388889,0.680000,0.702381,0.644068,0.0,1.0
332,0.298611,0.658182,0.666667,0.440678,1.0,0.0

In [43]:
penguins_y = penguins['species']
print(penguins_y)
penguins_y = penguins_y.astype('category').cat.codes.to_numpy()

features = torch.tensor(scaled_penguins_x.to_numpy(dtype=np.float32))
targets = torch.tensor(penguins_y, dtype=torch.long)
full_dataset = TensorDataset(features, targets)

val_size = int(len(full_dataset) * 0.1)
train_size = len(full_dataset) - val_size
train_dataset, val_dataset = random_split(
    full_dataset,
    [train_size, val_size],
    generator=torch.Generator().manual_seed(42),
)

train_loader = DataLoader(
    train_dataset,
    batch_size=64,
    shuffle=True,
    generator=torch.Generator().manual_seed(42),
)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)
full_loader = DataLoader(full_dataset, batch_size=64, shuffle=False)

def keras_batches(loader):
    while True:
        for x_batch, y_batch in loader:
            yield x_batch.numpy(), y_batch.numpy()

penguins_y

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...
328    Chinstrap
329    Chinstrap
330    Chinstrap
331    Chinstrap
332    Chinstrap
Name: species, Length: 333, dtype: object

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1], dtype=int8)

In [44]:
#construct the model
inputs = keras.Input(shape=(6,))
x = layers.Dense(7, activation = 'relu')(inputs)
x = layers.Dense(5, activation = 'relu')(x)
x = layers.Dense(3, activation = 'relu')(x)
outputs = layers.Dense(3, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model")

In [45]:
model.summary()

Model: "penguin_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_3 (InputLayer)        [(None, 6)]               0

 dense_8 (Dense)             (None, 7)                 49

 dense_9 (Dense)             (None, 5)                 40

 dense_10 (Dense)            (None, 3)                 18

 dense_11 (Dense)            (None, 3)                 12

=================================================================
Total params: 119 (476.00 Byte)
Trainable params: 119 (476.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [46]:
keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.

In [47]:
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(
    keras_batches(train_loader),
    steps_per_epoch=len(train_loader),
    epochs=100,
    validation_data=keras_batches(val_loader),
    validation_steps=len(val_loader),
)

scores = model.evaluate(keras_batches(full_loader), steps=len(full_loader), verbose=2)

Epoch 1/100

c:\Users\jfigg\.conda\envs\keras_env\Lib\site-packages\keras\src\backend.py:5714: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(

5/5 [==============================] - 1s 76ms/step - loss: 1.0938 - accuracy: 0.3933 - val_loss: 1.0916 - val_accuracy: 0.5152
Epoch 2/100
5/5 [==============================] - 0s 16ms/step - loss: 1.0902 - accuracy: 0.4433 - val_loss: 1.0898 - val_accuracy: 0.4848
Epoch 3/100
5/5 [==============================] - 0s 15ms/step - loss: 1.0878 - accuracy: 0.4333 - val_loss: 1.0884 - val_accuracy: 0.4848
Epoch 4/100
5/5 [==============================] - 0s 14ms/step - loss: 1.0855 - accuracy: 0.4333 - val_loss: 1.0869 - val_accuracy: 0.4848
Epoch 5/100
5/5 [==============================] - 0s 18ms/step - loss: 1.0834 - accuracy: 0.4333 - val_loss: 1.0855 - val_accuracy: 0.4848
Epoch 6/100
5/5 [==============================] - 0s 15ms/step - loss: 1.0813 - accuracy: 0.4333 - val_loss: 1.0842 - val_accuracy: 0.4848
Epoch 7/100
5/5 [==============================] - 0s 17ms/step - loss: 1.0792 - accuracy: 0.4333 - val_loss: 1.0827 - val_accuracy: 0.4848
Epoch 8/100
5/5 [==============================] - 0s 15ms/step - loss: 1.0771 - accuracy: 0.4333 - val_loss: 1.0812 - val_accuracy: 0.4848
Epoch 9/100
5/5 [==============================] - 0s 14ms/step - loss: 1.0748 - accuracy: 0.4333 - val_loss: 1.0795 - val_accuracy: 0.4848
Epoch 10/100
5/5 [==============================] - 0s 14ms/step - loss: 1.0711 - accuracy: 0.4333 - val_loss: 1.0698 - val_accuracy: 0.4848
Epoch 11/100
5/5 [==============================] - 0s 17ms/step - loss: 1.0664 - accuracy: 0.4333 - val_loss: 1.0661 - val_accuracy: 0.4848
Epoch 12/100
5/5 [==============================] - 0s 25ms/step - loss: 1.0629 - accuracy: 0.4333 - val_loss: 1.0639 - val_accuracy: 0.4848
Epoch 13/100
5/5 [==============================] - 0s 24ms/step - loss: 1.0598 - accuracy: 0.4333 - val_loss: 1.0610 - val_accuracy: 0.4848
Epoch 14/100
5/5 [==============================] - 0s 25ms/step - loss: 1.0567 - accuracy: 0.4333 - val_loss: 1.0580 - val_accuracy: 0.4848
Epoch 15/100
5/5 [==============================] - 0s 24ms/step - loss: 1.0537 - accuracy: 0.4333 - val_loss: 1.0562 - val_accuracy: 0.4848
Epoch 16/100
5/5 [==============================] - 0s 26ms/step - loss: 1.0506 - accuracy: 0.4333 - val_loss: 1.0520 - val_accuracy: 0.4848
Epoch 17/100
5/5 [==============================] - 0s 23ms/step - loss: 1.0475 - accuracy: 0.4333 - val_loss: 1.0486 - val_accuracy: 0.4848
Epoch 18/100
5/5 [==============================] - 0s 24ms/step - loss: 1.0442 - accuracy: 0.4333 - val_loss: 1.0466 - val_accuracy: 0.4848
Epoch 19/100
5/5 [==============================] - 0s 26ms/step - loss: 1.0410 - accuracy: 0.4333 - val_loss: 1.0441 - val_accuracy: 0.4848
Epoch 20/100
5/5 [==============================] - 0s 29ms/step - loss: 1.0380 - accuracy: 0.4333 - val_loss: 1.0410 - val_accuracy: 0.4848
Epoch 21/100
5/5 [==============================] - 0s 24ms/step - loss: 1.0342 - accuracy: 0.4333 - val_loss: 1.0361 - val_accuracy: 0.4848
Epoch 22/100
5/5 [==============================] - 0s 22ms/step - loss: 1.0308 - accuracy: 0.4333 - val_loss: 1.0347 - val_accuracy: 0.4848
Epoch 23/100
5/5 [==============================] - 0s 18ms/step - loss: 1.0272 - accuracy: 0.4333 - val_loss: 1.0313 - val_accuracy: 0.4848
Epoch 24/100
5/5 [==============================] - 0s 21ms/step - loss: 1.0233 - accuracy: 0.4333 - val_loss: 1.0257 - val_accuracy: 0.4848
Epoch 25/100
5/5 [==============================] - 0s 24ms/step - loss: 1.0201 - accuracy: 0.4333 - val_loss: 1.0225 - val_accuracy: 0.4848
Epoch 26/100
5/5 [==============================] - 0s 22ms/step - loss: 1.0160 - accuracy: 0.4333 - val_loss: 1.0204 - val_accuracy: 0.4848
Epoch 27/100
5/5 [==============================] - 0s 22ms/step - loss: 1.0121 - accuracy: 0.4333 - val_loss: 1.0162 - val_accuracy: 0.4848
Epoch 28/100
5/5 [==============================] - 0s 22ms/step - loss: 1.0081 - accuracy: 0.4333 - val_loss: 1.0126 - val_accuracy: 0.4848
Epoch 29/100
5/5 [==============================] - 0s 25ms/step - loss: 1.0043 - accuracy: 0.4333 - val_loss: 1.0089 - val_accuracy: 0.4848
Epoch 30/100
5/5 [==============================] - 0s 21ms/step - loss: 1.0001 - accuracy: 0.4333 - val_loss: 1.0058 - val_accuracy: 0.4848
Epoch 31/100
5/5 [==============================] - 0s 23ms/step - loss: 0.9962 - accuracy: 0.4333 - val_loss: 1.0010 - val_accuracy: 0.4848
Epoch 32/100
5/5 [==============================] - 0s 22ms/step - loss: 0.9918 - accuracy: 0.4333 - val_loss: 0.9963 - val_accuracy: 0.4848
Epoch 33/100
5/5 [==============================] - 0s 20ms/step - loss: 0.9878 - accuracy: 0.4333 - val_loss: 0.9942 - val_accuracy: 0.4848
Epoch 34/100
5/5 [==============================] - 0s 20ms/step - loss: 0.9833 - accuracy: 0.4333 - val_loss: 0.9892 - val_accuracy: 0.4848
Epoch 35/100
5/5 [==============================] - 0s 22ms/step - loss: 0.9788 - accuracy: 0.4333 - val_loss: 0.9854 - val_accuracy: 0.4848
Epoch 36/100
5/5 [==============================] - 0s 21ms/step - loss: 0.9740 - accuracy: 0.5333 - val_loss: 0.9805 - val_accuracy: 0.5455
Epoch 37/100
5/5 [==============================] - 0s 20ms/step - loss: 0.9690 - accuracy: 0.6067 - val_loss: 0.9759 - val_accuracy: 0.5758
Epoch 38/100
5/5 [==============================] - 0s 21ms/step - loss: 0.9640 - accuracy: 0.6167 - val_loss: 0.9717 - val_accuracy: 0.6061
Epoch 39/100
5/5 [==============================] - 0s 21ms/step - loss: 0.9587 - accuracy: 0.6267 - val_loss: 0.9678 - val_accuracy: 0.6364
Epoch 40/100
5/5 [==============================] - 0s 21ms/step - loss: 0.9534 - accuracy: 0.6500 - val_loss: 0.9608 - val_accuracy: 0.6061
Epoch 41/100
5/5 [==============================] - 0s 20ms/step - loss: 0.9481 - accuracy: 0.6400 - val_loss: 0.9566 - val_accuracy: 0.6364
Epoch 42/100
5/5 [==============================] - 0s 22ms/step - loss: 0.9428 - accuracy: 0.6533 - val_loss: 0.9511 - val_accuracy: 0.6364
Epoch 43/100
5/5 [==============================] - 0s 23ms/step - loss: 0.9372 - accuracy: 0.6667 - val_loss: 0.9457 - val_accuracy: 0.6364
Epoch 44/100
5/5 [==============================] - 0s 20ms/step - loss: 0.9318 - accuracy: 0.6600 - val_loss: 0.9415 - val_accuracy: 0.6364
Epoch 45/100
5/5 [==============================] - 0s 20ms/step - loss: 0.9259 - accuracy: 0.6733 - val_loss: 0.9357 - val_accuracy: 0.6364
Epoch 46/100
5/5 [==============================] - 0s 22ms/step - loss: 0.9203 - accuracy: 0.6833 - val_loss: 0.9297 - val_accuracy: 0.6364
Epoch 47/100
5/5 [==============================] - 0s 21ms/step - loss: 0.9145 - accuracy: 0.6867 - val_loss: 0.9250 - val_accuracy: 0.6667
Epoch 48/100
5/5 [==============================] - 0s 23ms/step - loss: 0.9085 - accuracy: 0.7233 - val_loss: 0.9176 - val_accuracy: 0.6364
Epoch 49/100
5/5 [==============================] - 0s 21ms/step - loss: 0.9024 - accuracy: 0.7133 - val_loss: 0.9113 - val_accuracy: 0.6364
Epoch 50/100
5/5 [==============================] - 0s 21ms/step - loss: 0.8972 - accuracy: 0.7033 - val_loss: 0.9089 - val_accuracy: 0.6667
Epoch 51/100
5/5 [==============================] - 0s 22ms/step - loss: 0.8912 - accuracy: 0.7333 - val_loss: 0.9032 - val_accuracy: 0.6667
Epoch 52/100
5/5 [==============================] - 0s 23ms/step - loss: 0.8854 - accuracy: 0.7200 - val_loss: 0.8976 - val_accuracy: 0.6667
Epoch 53/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8794 - accuracy: 0.7367 - val_loss: 0.8938 - val_accuracy: 0.6970
Epoch 54/100
5/5 [==============================] - 0s 19ms/step - loss: 0.8733 - accuracy: 0.7467 - val_loss: 0.8870 - val_accuracy: 0.6667
Epoch 55/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8670 - accuracy: 0.7433 - val_loss: 0.8821 - val_accuracy: 0.6970
Epoch 56/100
5/5 [==============================] - 0s 15ms/step - loss: 0.8610 - accuracy: 0.7500 - val_loss: 0.8768 - val_accuracy: 0.6970
Epoch 57/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8549 - accuracy: 0.7600 - val_loss: 0.8711 - val_accuracy: 0.6970
Epoch 58/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8495 - accuracy: 0.7567 - val_loss: 0.8656 - val_accuracy: 0.6970
Epoch 59/100
5/5 [==============================] - 0s 18ms/step - loss: 0.8431 - accuracy: 0.7667 - val_loss: 0.8603 - val_accuracy: 0.6970
Epoch 60/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8374 - accuracy: 0.7633 - val_loss: 0.8565 - val_accuracy: 0.6970
Epoch 61/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8319 - accuracy: 0.7767 - val_loss: 0.8509 - val_accuracy: 0.6970
Epoch 62/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8263 - accuracy: 0.7833 - val_loss: 0.8471 - val_accuracy: 0.6970
Epoch 63/100
5/5 [==============================] - 0s 19ms/step - loss: 0.8206 - accuracy: 0.7867 - val_loss: 0.8423 - val_accuracy: 0.6970
Epoch 64/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8147 - accuracy: 0.7833 - val_loss: 0.8372 - val_accuracy: 0.6970
Epoch 65/100
5/5 [==============================] - 0s 20ms/step - loss: 0.8092 - accuracy: 0.7867 - val_loss: 0.8300 - val_accuracy: 0.6970
Epoch 66/100
5/5 [==============================] - 0s 21ms/step - loss: 0.8033 - accuracy: 0.7867 - val_loss: 0.8264 - val_accuracy: 0.6970
Epoch 67/100
5/5 [==============================] - 0s 21ms/step - loss: 0.7976 - accuracy: 0.7933 - val_loss: 0.8207 - val_accuracy: 0.6970
Epoch 68/100
5/5 [==============================] - 0s 20ms/step - loss: 0.7918 - accuracy: 0.7900 - val_loss: 0.8159 - val_accuracy: 0.6970
Epoch 69/100
5/5 [==============================] - 0s 20ms/step - loss: 0.7861 - accuracy: 0.7933 - val_loss: 0.8112 - val_accuracy: 0.6970
Epoch 70/100
5/5 [==============================] - 0s 20ms/step - loss: 0.7804 - accuracy: 0.7967 - val_loss: 0.8067 - val_accuracy: 0.6970
Epoch 71/100
5/5 [==============================] - 0s 20ms/step - loss: 0.7753 - accuracy: 0.7933 - val_loss: 0.8048 - val_accuracy: 0.6970
Epoch 72/100
5/5 [==============================] - 0s 19ms/step - loss: 0.7704 - accuracy: 0.7967 - val_loss: 0.8011 - val_accuracy: 0.6970
Epoch 73/100
5/5 [==============================] - 0s 19ms/step - loss: 0.7652 - accuracy: 0.7967 - val_loss: 0.7962 - val_accuracy: 0.6970
Epoch 74/100
5/5 [==============================] - 0s 20ms/step - loss: 0.7602 - accuracy: 0.8000 - val_loss: 0.7919 - val_accuracy: 0.6970
Epoch 75/100
5/5 [==============================] - 0s 19ms/step - loss: 0.7553 - accuracy: 0.8000 - val_loss: 0.7890 - val_accuracy: 0.6970
Epoch 76/100
5/5 [==============================] - 0s 22ms/step - loss: 0.7505 - accuracy: 0.8000 - val_loss: 0.7857 - val_accuracy: 0.6970
Epoch 77/100
5/5 [==============================] - 0s 20ms/step - loss: 0.7460 - accuracy: 0.8000 - val_loss: 0.7803 - val_accuracy: 0.6970
Epoch 78/100
5/5 [==============================] - 0s 20ms/step - loss: 0.7414 - accuracy: 0.8000 - val_loss: 0.7766 - val_accuracy: 0.6970
Epoch 79/100
5/5 [==============================] - 0s 21ms/step - loss: 0.7368 - accuracy: 0.8000 - val_loss: 0.7737 - val_accuracy: 0.6970
Epoch 80/100
5/5 [==============================] - 0s 19ms/step - loss: 0.7327 - accuracy: 0.8000 - val_loss: 0.7727 - val_accuracy: 0.6970
Epoch 81/100
5/5 [==============================] - 0s 19ms/step - loss: 0.7286 - accuracy: 0.8033 - val_loss: 0.7676 - val_accuracy: 0.6970
Epoch 82/100
5/5 [==============================] - 0s 19ms/step - loss: 0.7242 - accuracy: 0.8000 - val_loss: 0.7655 - val_accuracy: 0.6970
Epoch 83/100
5/5 [==============================] - 0s 18ms/step - loss: 0.7203 - accuracy: 0.8000 - val_loss: 0.7631 - val_accuracy: 0.6970
Epoch 84/100
5/5 [==============================] - 0s 18ms/step - loss: 0.7161 - accuracy: 0.8033 - val_loss: 0.7581 - val_accuracy: 0.6970
Epoch 85/100
5/5 [==============================] - 0s 18ms/step - loss: 0.7124 - accuracy: 0.8000 - val_loss: 0.7561 - val_accuracy: 0.6970
Epoch 86/100
5/5 [==============================] - 0s 20ms/step - loss: 0.7082 - accuracy: 0.8033 - val_loss: 0.7523 - val_accuracy: 0.6970
Epoch 87/100
5/5 [==============================] - 0s 21ms/step - loss: 0.7045 - accuracy: 0.8033 - val_loss: 0.7495 - val_accuracy: 0.6970
Epoch 88/100
5/5 [==============================] - 0s 19ms/step - loss: 0.7005 - accuracy: 0.8033 - val_loss: 0.7484 - val_accuracy: 0.6970
Epoch 89/100
5/5 [==============================] - 0s 22ms/step - loss: 0.6969 - accuracy: 0.8033 - val_loss: 0.7454 - val_accuracy: 0.6970
Epoch 90/100
5/5 [==============================] - 0s 19ms/step - loss: 0.6932 - accuracy: 0.8033 - val_loss: 0.7423 - val_accuracy: 0.6970
Epoch 91/100
5/5 [==============================] - 0s 18ms/step - loss: 0.6895 - accuracy: 0.8033 - val_loss: 0.7399 - val_accuracy: 0.6970
Epoch 92/100
5/5 [==============================] - 0s 19ms/step - loss: 0.6860 - accuracy: 0.8033 - val_loss: 0.7362 - val_accuracy: 0.6970
Epoch 93/100
5/5 [==============================] - 0s 19ms/step - loss: 0.6824 - accuracy: 0.8033 - val_loss: 0.7342 - val_accuracy: 0.6970
Epoch 94/100
5/5 [==============================] - 0s 17ms/step - loss: 0.6789 - accuracy: 0.8033 - val_loss: 0.7312 - val_accuracy: 0.6970
Epoch 95/100
5/5 [==============================] - 0s 19ms/step - loss: 0.6755 - accuracy: 0.8033 - val_loss: 0.7299 - val_accuracy: 0.6970
Epoch 96/100
5/5 [==============================] - 0s 17ms/step - loss: 0.6725 - accuracy: 0.8033 - val_loss: 0.7269 - val_accuracy: 0.6970
Epoch 97/100
5/5 [==============================] - 0s 20ms/step - loss: 0.6690 - accuracy: 0.8033 - val_loss: 0.7239 - val_accuracy: 0.6970
Epoch 98/100
5/5 [==============================] - 0s 20ms/step - loss: 0.6666 - accuracy: 0.8033 - val_loss: 0.7222 - val_accuracy: 0.6970
Epoch 99/100
5/5 [==============================] - 0s 19ms/step - loss: 0.6632 - accuracy: 0.8033 - val_loss: 0.7199 - val_accuracy: 0.6970
Epoch 100/100
5/5 [==============================] - 0s 22ms/step - loss: 0.6603 - accuracy: 0.8033 - val_loss: 0.7172 - val_accuracy: 0.6970
6/6 - 0s - loss: 0.6640 - accuracy: 0.7928 - 77ms/epoch - 13ms/step

In [53]:
model_logit_true = keras.Model(inputs=inputs, outputs=outputs, name="penguin_model_scaled")

model_logit_true.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history_logit_true = model_logit_true.fit(
    keras_batches(train_loader),
    steps_per_epoch=len(train_loader),
    epochs=100,
    validation_data=keras_batches(val_loader),
    validation_steps=len(val_loader),
)

scores = model_logit_true.evaluate(keras_batches(full_loader), steps=len(full_loader), verbose = 2)

Epoch 1/100
5/5 [==============================] - 1s 61ms/step - loss: 0.3356 - accuracy: 0.8433 - val_loss: 0.4569 - val_accuracy: 0.6970
Epoch 2/100
5/5 [==============================] - 0s 18ms/step - loss: 0.3333 - accuracy: 0.8533 - val_loss: 0.4565 - val_accuracy: 0.6970
Epoch 3/100
5/5 [==============================] - 0s 18ms/step - loss: 0.3333 - accuracy: 0.8500 - val_loss: 0.4554 - val_accuracy: 0.6970
Epoch 4/100
5/5 [==============================] - 0s 16ms/step - loss: 0.3313 - accuracy: 0.8567 - val_loss: 0.4549 - val_accuracy: 0.6970
Epoch 5/100
5/5 [==============================] - 0s 15ms/step - loss: 0.3305 - accuracy: 0.8533 - val_loss: 0.4554 - val_accuracy: 0.6970
Epoch 6/100
5/5 [==============================] - 0s 16ms/step - loss: 0.3298 - accuracy: 0.8433 - val_loss: 0.4531 - val_accuracy: 0.6970
Epoch 7/100
5/5 [==============================] - 0s 16ms/step - loss: 0.3286 - accuracy: 0.8467 - val_loss: 0.4513 - val_accuracy: 0.6970
Epoch 8/100
5/5 [==============================] - 0s 17ms/step - loss: 0.3282 - accuracy: 0.8533 - val_loss: 0.4500 - val_accuracy: 0.6970
Epoch 9/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3272 - accuracy: 0.8567 - val_loss: 0.4497 - val_accuracy: 0.6970
Epoch 10/100
5/5 [==============================] - 0s 17ms/step - loss: 0.3261 - accuracy: 0.8533 - val_loss: 0.4486 - val_accuracy: 0.6970
Epoch 11/100
5/5 [==============================] - 0s 15ms/step - loss: 0.3255 - accuracy: 0.8500 - val_loss: 0.4476 - val_accuracy: 0.6970
Epoch 12/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3253 - accuracy: 0.8567 - val_loss: 0.4467 - val_accuracy: 0.6970
Epoch 13/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3233 - accuracy: 0.8533 - val_loss: 0.4459 - val_accuracy: 0.6970
Epoch 14/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3230 - accuracy: 0.8533 - val_loss: 0.4447 - val_accuracy: 0.6970
Epoch 15/100
5/5 [==============================] - 0s 16ms/step - loss: 0.3235 - accuracy: 0.8600 - val_loss: 0.4451 - val_accuracy: 0.6970
Epoch 16/100
5/5 [==============================] - 0s 15ms/step - loss: 0.3212 - accuracy: 0.8567 - val_loss: 0.4438 - val_accuracy: 0.6970
Epoch 17/100
5/5 [==============================] - 0s 12ms/step - loss: 0.3204 - accuracy: 0.8567 - val_loss: 0.4428 - val_accuracy: 0.6970
Epoch 18/100
5/5 [==============================] - 0s 12ms/step - loss: 0.3199 - accuracy: 0.8567 - val_loss: 0.4427 - val_accuracy: 0.6970
Epoch 19/100
5/5 [==============================] - 0s 11ms/step - loss: 0.3194 - accuracy: 0.8500 - val_loss: 0.4412 - val_accuracy: 0.6970
Epoch 20/100
5/5 [==============================] - 0s 12ms/step - loss: 0.3180 - accuracy: 0.8567 - val_loss: 0.4407 - val_accuracy: 0.6970
Epoch 21/100
5/5 [==============================] - 0s 17ms/step - loss: 0.3176 - accuracy: 0.8567 - val_loss: 0.4401 - val_accuracy: 0.6970
Epoch 22/100
5/5 [==============================] - 0s 11ms/step - loss: 0.3162 - accuracy: 0.8567 - val_loss: 0.4398 - val_accuracy: 0.6970
Epoch 23/100
5/5 [==============================] - 0s 13ms/step - loss: 0.3162 - accuracy: 0.8567 - val_loss: 0.4388 - val_accuracy: 0.6970
Epoch 24/100
5/5 [==============================] - 0s 15ms/step - loss: 0.3146 - accuracy: 0.8567 - val_loss: 0.4382 - val_accuracy: 0.7576
Epoch 25/100
5/5 [==============================] - 0s 22ms/step - loss: 0.3148 - accuracy: 0.8633 - val_loss: 0.4382 - val_accuracy: 0.6970
Epoch 26/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3138 - accuracy: 0.8567 - val_loss: 0.4377 - val_accuracy: 0.6970
Epoch 27/100
5/5 [==============================] - 0s 15ms/step - loss: 0.3126 - accuracy: 0.8567 - val_loss: 0.4363 - val_accuracy: 0.6970
Epoch 28/100
5/5 [==============================] - 0s 13ms/step - loss: 0.3124 - accuracy: 0.8567 - val_loss: 0.4351 - val_accuracy: 0.7273
Epoch 29/100
5/5 [==============================] - 0s 16ms/step - loss: 0.3117 - accuracy: 0.8600 - val_loss: 0.4349 - val_accuracy: 0.6970
Epoch 30/100
5/5 [==============================] - 0s 15ms/step - loss: 0.3107 - accuracy: 0.8600 - val_loss: 0.4341 - val_accuracy: 0.6970
Epoch 31/100
5/5 [==============================] - 0s 16ms/step - loss: 0.3094 - accuracy: 0.8600 - val_loss: 0.4335 - val_accuracy: 0.6970
Epoch 32/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3088 - accuracy: 0.8600 - val_loss: 0.4326 - val_accuracy: 0.6970
Epoch 33/100
5/5 [==============================] - 0s 12ms/step - loss: 0.3082 - accuracy: 0.8567 - val_loss: 0.4320 - val_accuracy: 0.7576
Epoch 34/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3074 - accuracy: 0.8600 - val_loss: 0.4315 - val_accuracy: 0.6970
Epoch 35/100
5/5 [==============================] - 0s 13ms/step - loss: 0.3066 - accuracy: 0.8600 - val_loss: 0.4305 - val_accuracy: 0.7879
Epoch 36/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3063 - accuracy: 0.8600 - val_loss: 0.4294 - val_accuracy: 0.7879
Epoch 37/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3051 - accuracy: 0.8600 - val_loss: 0.4294 - val_accuracy: 0.7576
Epoch 38/100
5/5 [==============================] - 0s 15ms/step - loss: 0.3040 - accuracy: 0.8633 - val_loss: 0.4280 - val_accuracy: 0.7273
Epoch 39/100
5/5 [==============================] - 0s 15ms/step - loss: 0.3034 - accuracy: 0.8600 - val_loss: 0.4262 - val_accuracy: 0.7576
Epoch 40/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3050 - accuracy: 0.8667 - val_loss: 0.4255 - val_accuracy: 0.7879
Epoch 41/100
5/5 [==============================] - 0s 17ms/step - loss: 0.3026 - accuracy: 0.8600 - val_loss: 0.4255 - val_accuracy: 0.7879
Epoch 42/100
5/5 [==============================] - 0s 16ms/step - loss: 0.3012 - accuracy: 0.8633 - val_loss: 0.4252 - val_accuracy: 0.7576
Epoch 43/100
5/5 [==============================] - 0s 16ms/step - loss: 0.3010 - accuracy: 0.8700 - val_loss: 0.4259 - val_accuracy: 0.6970
Epoch 44/100
5/5 [==============================] - 0s 14ms/step - loss: 0.3006 - accuracy: 0.8600 - val_loss: 0.4248 - val_accuracy: 0.7576
Epoch 45/100
5/5 [==============================] - 0s 16ms/step - loss: 0.2996 - accuracy: 0.8600 - val_loss: 0.4237 - val_accuracy: 0.7879
Epoch 46/100
5/5 [==============================] - 0s 16ms/step - loss: 0.2986 - accuracy: 0.8633 - val_loss: 0.4226 - val_accuracy: 0.7879
Epoch 47/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2982 - accuracy: 0.8633 - val_loss: 0.4225 - val_accuracy: 0.7879
Epoch 48/100
5/5 [==============================] - 0s 17ms/step - loss: 0.2970 - accuracy: 0.8633 - val_loss: 0.4227 - val_accuracy: 0.7879
Epoch 49/100
5/5 [==============================] - 0s 16ms/step - loss: 0.2964 - accuracy: 0.8667 - val_loss: 0.4203 - val_accuracy: 0.7879
Epoch 50/100
5/5 [==============================] - 0s 16ms/step - loss: 0.2963 - accuracy: 0.8600 - val_loss: 0.4200 - val_accuracy: 0.7879
Epoch 51/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2953 - accuracy: 0.8633 - val_loss: 0.4190 - val_accuracy: 0.7879
Epoch 52/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2941 - accuracy: 0.8733 - val_loss: 0.4180 - val_accuracy: 0.7879
Epoch 53/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2936 - accuracy: 0.8700 - val_loss: 0.4175 - val_accuracy: 0.7576
Epoch 54/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2931 - accuracy: 0.8667 - val_loss: 0.4160 - val_accuracy: 0.7879
Epoch 55/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2928 - accuracy: 0.8700 - val_loss: 0.4158 - val_accuracy: 0.7879
Epoch 56/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2922 - accuracy: 0.8667 - val_loss: 0.4151 - val_accuracy: 0.7879
Epoch 57/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2912 - accuracy: 0.8700 - val_loss: 0.4140 - val_accuracy: 0.7879
Epoch 58/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2915 - accuracy: 0.8767 - val_loss: 0.4139 - val_accuracy: 0.7879
Epoch 59/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2896 - accuracy: 0.8733 - val_loss: 0.4130 - val_accuracy: 0.7879
Epoch 60/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2892 - accuracy: 0.8800 - val_loss: 0.4130 - val_accuracy: 0.7879
Epoch 61/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2891 - accuracy: 0.8733 - val_loss: 0.4126 - val_accuracy: 0.7879
Epoch 62/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2873 - accuracy: 0.8700 - val_loss: 0.4115 - val_accuracy: 0.7879
Epoch 63/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2863 - accuracy: 0.8767 - val_loss: 0.4105 - val_accuracy: 0.7879
Epoch 64/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2869 - accuracy: 0.8767 - val_loss: 0.4091 - val_accuracy: 0.7879
Epoch 65/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2854 - accuracy: 0.8867 - val_loss: 0.4075 - val_accuracy: 0.7879
Epoch 66/100
5/5 [==============================] - 0s 12ms/step - loss: 0.2854 - accuracy: 0.8800 - val_loss: 0.4074 - val_accuracy: 0.7879
Epoch 67/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2839 - accuracy: 0.8800 - val_loss: 0.4063 - val_accuracy: 0.7879
Epoch 68/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2841 - accuracy: 0.8800 - val_loss: 0.4061 - val_accuracy: 0.7879
Epoch 69/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2833 - accuracy: 0.8833 - val_loss: 0.4065 - val_accuracy: 0.7879
Epoch 70/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2825 - accuracy: 0.8767 - val_loss: 0.4056 - val_accuracy: 0.7879
Epoch 71/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2825 - accuracy: 0.8833 - val_loss: 0.4044 - val_accuracy: 0.7879
Epoch 72/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2807 - accuracy: 0.8867 - val_loss: 0.4046 - val_accuracy: 0.7879
Epoch 73/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2801 - accuracy: 0.8867 - val_loss: 0.4040 - val_accuracy: 0.7879
Epoch 74/100
5/5 [==============================] - 0s 12ms/step - loss: 0.2806 - accuracy: 0.8900 - val_loss: 0.4037 - val_accuracy: 0.7879
Epoch 75/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2798 - accuracy: 0.8833 - val_loss: 0.4026 - val_accuracy: 0.7879
Epoch 76/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2787 - accuracy: 0.8800 - val_loss: 0.4013 - val_accuracy: 0.7879
Epoch 77/100
5/5 [==============================] - 0s 11ms/step - loss: 0.2779 - accuracy: 0.8867 - val_loss: 0.4011 - val_accuracy: 0.7879
Epoch 78/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2770 - accuracy: 0.8867 - val_loss: 0.4015 - val_accuracy: 0.7879
Epoch 79/100
5/5 [==============================] - 0s 16ms/step - loss: 0.2765 - accuracy: 0.8867 - val_loss: 0.4017 - val_accuracy: 0.7879
Epoch 80/100
5/5 [==============================] - 0s 20ms/step - loss: 0.2756 - accuracy: 0.8867 - val_loss: 0.4008 - val_accuracy: 0.7879
Epoch 81/100
5/5 [==============================] - 0s 17ms/step - loss: 0.2753 - accuracy: 0.8933 - val_loss: 0.4004 - val_accuracy: 0.7879
Epoch 82/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2746 - accuracy: 0.8867 - val_loss: 0.3995 - val_accuracy: 0.7879
Epoch 83/100
5/5 [==============================] - 0s 12ms/step - loss: 0.2739 - accuracy: 0.8967 - val_loss: 0.4000 - val_accuracy: 0.7879
Epoch 84/100
5/5 [==============================] - 0s 12ms/step - loss: 0.2738 - accuracy: 0.8867 - val_loss: 0.3973 - val_accuracy: 0.7879
Epoch 85/100
5/5 [==============================] - 0s 18ms/step - loss: 0.2723 - accuracy: 0.8900 - val_loss: 0.3969 - val_accuracy: 0.7879
Epoch 86/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2720 - accuracy: 0.8867 - val_loss: 0.3950 - val_accuracy: 0.7879
Epoch 87/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2711 - accuracy: 0.8900 - val_loss: 0.3943 - val_accuracy: 0.7879
Epoch 88/100
5/5 [==============================] - 0s 15ms/step - loss: 0.2708 - accuracy: 0.9033 - val_loss: 0.3951 - val_accuracy: 0.7879
Epoch 89/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2704 - accuracy: 0.8867 - val_loss: 0.3934 - val_accuracy: 0.7879
Epoch 90/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2701 - accuracy: 0.9000 - val_loss: 0.3928 - val_accuracy: 0.7879
Epoch 91/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2689 - accuracy: 0.8900 - val_loss: 0.3917 - val_accuracy: 0.7879
Epoch 92/100
5/5 [==============================] - 0s 12ms/step - loss: 0.2681 - accuracy: 0.9000 - val_loss: 0.3909 - val_accuracy: 0.7879
Epoch 93/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2675 - accuracy: 0.8967 - val_loss: 0.3918 - val_accuracy: 0.7879
Epoch 94/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2681 - accuracy: 0.9000 - val_loss: 0.3915 - val_accuracy: 0.7879
Epoch 95/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2673 - accuracy: 0.9000 - val_loss: 0.3909 - val_accuracy: 0.7879
Epoch 96/100
5/5 [==============================] - 0s 14ms/step - loss: 0.2662 - accuracy: 0.8900 - val_loss: 0.3904 - val_accuracy: 0.7879
Epoch 97/100
5/5 [==============================] - 0s 12ms/step - loss: 0.2655 - accuracy: 0.9000 - val_loss: 0.3900 - val_accuracy: 0.7879
Epoch 98/100
5/5 [==============================] - 0s 11ms/step - loss: 0.2651 - accuracy: 0.9000 - val_loss: 0.3890 - val_accuracy: 0.7879
Epoch 99/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2649 - accuracy: 0.8900 - val_loss: 0.3881 - val_accuracy: 0.7879
Epoch 100/100
5/5 [==============================] - 0s 13ms/step - loss: 0.2635 - accuracy: 0.8933 - val_loss: 0.3880 - val_accuracy: 0.7879
6/6 - 0s - loss: 0.2747 - accuracy: 0.8919 - 51ms/epoch - 9ms/step

In [49]:
model_logit_true.predict(scaled_penguins_x)

11/11 [==============================] - 0s 2ms/step

array([[8.93261373e-01, 1.06719762e-01, 1.88058966e-05],
       [8.27006996e-01, 1.72605395e-01, 3.87688546e-04],
       [8.25148225e-01, 1.74436331e-01, 4.15366259e-04],
       [9.16729152e-01, 8.32667127e-02, 4.20173501e-06],
       [9.22641218e-01, 7.73560032e-02, 2.70906321e-06],
       [8.73775303e-01, 1.26171872e-01, 5.27817210e-05],
       [8.79898012e-01, 1.20063156e-01, 3.87937325e-05],
       [8.44251335e-01, 1.55550808e-01, 1.97819711e-04],
       [9.31367874e-01, 6.86307251e-02, 1.33369656e-06],
       [9.39473927e-01, 6.05254173e-02, 6.37213589e-07],
       [8.84580731e-01, 1.15388870e-01, 3.03609831e-05],
       [8.85057628e-01, 1.14912756e-01, 2.95978043e-05],
       [8.84138525e-01, 1.15830429e-01, 3.10837495e-05],
       [9.18272436e-01, 8.17238316e-02, 3.75762716e-06],
       [8.89472425e-01, 1.10504240e-01, 2.32755010e-05],
       [9.13330197e-01, 8.66645426e-02, 5.33835964e-06],
       [9.03205633e-01, 9.67840031e-02, 1.03820057e-05],
       [9.23514783e-01, 7.64826983e-02, 2.53230951e-06],
       [8.67321432e-01, 1.32606626e-01, 7.20005555e-05],
       [8.37559223e-01, 1.62181988e-01, 2.58754153e-04],
       [9.23705041e-01, 7.62923807e-02, 2.49510958e-06],
       [8.71502221e-01, 1.28438771e-01, 5.89741830e-05],
       [8.48424852e-01, 1.51408657e-01, 1.66455575e-04],
       [9.15047169e-01, 8.49481970e-02, 4.73548334e-06],
       [8.87634635e-01, 1.12339601e-01, 2.57507654e-05],
       [8.34246099e-01, 1.65459454e-01, 2.94491183e-04],
       [8.96094620e-01, 1.03889458e-01, 1.59619940e-05],
       [8.50574255e-01, 1.49273694e-01, 1.52047403e-04],
       [8.73537898e-01, 1.26408696e-01, 5.34013525e-05],
       [8.25084746e-01, 1.74498856e-01, 4.16341354e-04],
       [9.27564025e-01, 7.24340901e-02, 1.83426607e-06],
       [9.14393842e-01, 8.56012702e-02, 4.95770200e-06],
       [8.71098220e-01, 1.28841639e-01, 6.01376196e-05],
       [9.23459351e-01, 7.65381083e-02, 2.54322708e-06],
       [8.84498537e-01, 1.15470953e-01, 3.04942496e-05],
       [9.07374561e-01, 9.26174521e-02, 7.95892811e-06],
       [8.15410256e-01, 1.83999673e-01, 5.90054260e-04],
       [9.14003015e-01, 8.59919265e-02, 5.09479787e-06],
       [8.25949252e-01, 1.73647538e-01, 4.03237063e-04],
       [8.56009662e-01, 1.43869966e-01, 1.20305485e-04],
       [8.58399689e-01, 1.41492099e-01, 1.08268032e-04],
       [8.85523736e-01, 1.14447452e-01, 2.88678675e-05],
       [8.84538472e-01, 1.15431048e-01, 3.04293881e-05],
       [9.17887032e-01, 8.21091160e-02, 3.86462898e-06],
       [8.47416461e-01, 1.52409822e-01, 1.73610460e-04],
       [8.66393149e-01, 1.33531719e-01, 7.52059423e-05],
       [8.94062042e-01, 1.05919860e-01, 1.79615836e-05],
       [8.35033178e-01, 1.64681271e-01, 2.85637536e-04],
       [9.09683168e-01, 9.03099924e-02, 6.83708913e-06],
       [8.34873796e-01, 1.64838806e-01, 2.87410890e-04],
       [8.44376445e-01, 1.55426815e-01, 1.96811161e-04],
       [8.46661508e-01, 1.53159365e-01, 1.79140305e-04],
       [8.64656687e-01, 1.35261744e-01, 8.15313542e-05],
       [8.89257789e-01, 1.10718690e-01, 2.35537955e-05],
       [8.68083000e-01, 1.31847516e-01, 6.94590199e-05],
       [9.12878752e-01, 8.71157199e-02, 5.50720597e-06],
       [8.40598047e-01, 1.59172595e-01, 2.29331941e-04],
       [8.09386134e-01, 1.89886674e-01, 7.27217470e-04],
       [8.77146125e-01, 1.22809216e-01, 4.46270242e-05],
       [7.91587651e-01, 2.07107797e-01, 1.30447827e-03],
       [7.95135379e-01, 2.03699261e-01, 1.16543518e-03],
       [8.65772545e-01, 1.34150073e-01, 7.74164801e-05],
       [8.36806357e-01, 1.62927136e-01, 2.66528077e-04],
       [8.34319353e-01, 1.65386915e-01, 2.93656311e-04],
       [9.27858591e-01, 7.21396655e-02, 1.79058122e-06],
       [8.47967148e-01, 1.51863232e-01, 1.69671795e-04],
       [7.76536047e-01, 2.21400157e-01, 2.06387090e-03],
       [7.49235272e-01, 2.46362463e-01, 4.40226542e-03],
       [8.69594097e-01, 1.30341217e-01, 6.46435146e-05],
       [7.84273028e-01, 2.14090362e-01, 1.63656799e-03],
       [7.49042273e-01, 2.46533304e-01, 4.42447327e-03],
       [9.15528357e-01, 8.44670832e-02, 4.57722672e-06],
       [8.08824539e-01, 1.90434173e-01, 7.41301221e-04],
       [8.32120538e-01, 1.67559847e-01, 3.19595361e-04],
       [8.79061341e-01, 1.20898224e-01, 4.04939856e-05],
       [6.97256386e-01, 2.88137734e-01, 1.46058993e-02],
       [9.10669267e-01, 8.93243700e-02, 6.40052667e-06],
       [9.16439593e-01, 8.35560858e-02, 4.28978183e-06],
       [8.65613818e-01, 1.34308219e-01, 7.79906113e-05],
       [8.97873223e-01, 1.02112427e-01, 1.43707648e-05],
       [9.16168690e-01, 8.38269368e-02, 4.37360177e-06],
       [9.02382791e-01, 9.76062492e-02, 1.09275861e-05],
       [8.96393597e-01, 1.03590675e-01, 1.56844289e-05],
       [8.86963785e-01, 1.13009468e-01, 2.67085961e-05],
       [8.53087902e-01, 1.46775514e-01, 1.36571849e-04],
       [7.38670170e-01, 2.55569488e-01, 5.76036423e-03],
       [8.89057517e-01, 1.10918596e-01, 2.38157809e-05],
       [8.41367841e-01, 1.58409864e-01, 2.22355186e-04],
       [8.70256066e-01, 1.29681304e-01, 6.26261390e-05],
       [7.84577310e-01, 2.13801235e-01, 1.62143866e-03],
       [8.85753453e-01, 1.14217989e-01, 2.85136230e-05],
       [8.17570686e-01, 1.81882650e-01, 5.46630064e-04],
       [8.84035170e-01, 1.15933523e-01, 3.12546508e-05],
       [7.93164730e-01, 2.05594212e-01, 1.24100584e-03],
       [8.84294033e-01, 1.15675129e-01, 3.08279268e-05],
       [8.51857066e-01, 1.47998929e-01, 1.43970727e-04],
       [8.08110714e-01, 1.91129819e-01, 7.59543618e-04],
       [9.19457316e-01, 8.05392787e-02, 3.44419664e-06],
       [8.92096579e-01, 1.07883334e-01, 2.00944178e-05],
       [8.89143646e-01, 1.10832646e-01, 2.37028180e-05],
       [7.74346709e-01, 2.23452508e-01, 2.20073410e-03],
       [9.18875992e-01, 8.11204314e-02, 3.59508545e-06],
       [8.57268572e-01, 1.42617613e-01, 1.13829105e-04],
       [7.89204180e-01, 2.09390193e-01, 1.40568730e-03],
       [7.41304100e-01, 2.53302395e-01, 5.39351860e-03],
       [8.49878311e-01, 1.49965122e-01, 1.56590177e-04],
       [8.26723754e-01, 1.72884420e-01, 3.91798938e-04],
       [8.39731932e-01, 1.60030589e-01, 2.37407119e-04],
       [9.31550562e-01, 6.84480742e-02, 1.31289755e-06],
       [7.71809697e-01, 2.25821450e-01, 2.36889371e-03],
       [8.31757069e-01, 1.67918906e-01, 3.24068649e-04],
       [9.22755539e-01, 7.72418678e-02, 2.68538565e-06],
       [8.55595291e-01, 1.44282177e-01, 1.22505764e-04],
       [8.50303769e-01, 1.49542466e-01, 1.53799585e-04],
       [8.68881285e-01, 1.31051838e-01, 6.68781940e-05],
       [9.04288709e-01, 9.57016125e-02, 9.69924622e-06],
       [8.42914939e-01, 1.56876162e-01, 2.08883415e-04],
       [7.83365190e-01, 2.14952469e-01, 1.68243027e-03],
       [8.27170551e-01, 1.72444135e-01, 3.85329971e-04],
       [8.33202124e-01, 1.66491285e-01, 3.06599628e-04],
       [8.39689434e-01, 1.60072789e-01, 2.37810455e-04],
       [7.92655706e-01, 2.06083089e-01, 1.26119796e-03],
       [8.15912783e-01, 1.83507517e-01, 5.79696847e-04],
       [6.23119295e-01, 3.27311367e-01, 4.95693199e-02],
       [8.59879196e-01, 1.40019476e-01, 1.01347803e-04],
       [8.23227704e-01, 1.76326543e-01, 4.45743062e-04],
       [8.89776766e-01, 1.10200301e-01, 2.28859008e-05],
       [8.43207717e-01, 1.56585872e-01, 2.06415236e-04],
       [8.59176993e-01, 1.40718415e-01, 1.04583109e-04],
       [7.78644562e-01, 2.19416544e-01, 1.93896028e-03],
       [8.75032187e-01, 1.24918178e-01, 4.96034299e-05],
       [8.82438898e-01, 1.17527165e-01, 3.39998041e-05],
       [8.28428566e-01, 1.71203852e-01, 3.67607136e-04],
       [8.06711316e-01, 1.92492157e-01, 7.96425564e-04],
       [7.78307438e-01, 2.19734028e-01, 1.95848383e-03],
       [7.88907766e-01, 2.09673434e-01, 1.41872629e-03],
       [8.41917038e-01, 1.57865509e-01, 2.17489578e-04],
       [7.55734265e-01, 2.40559116e-01, 3.70660820e-03],
       [8.21297824e-01, 1.78223953e-01, 4.78180067e-04],
       [8.85260046e-01, 1.14710778e-01, 2.92790137e-05],
       [8.58598948e-01, 1.41293779e-01, 1.07312990e-04],
       [9.10498738e-01, 8.94946903e-02, 6.47423030e-06],
       [8.65713418e-01, 1.34208962e-01, 7.76297238e-05],
       [8.49889159e-01, 1.49954304e-01, 1.56518261e-04],
       [8.56186748e-01, 1.43693760e-01, 1.19375509e-04],
       [7.83950567e-01, 2.14396715e-01, 1.65273447e-03],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [1.52329296e-01, 1.65160909e-01, 6.82509840e-01],
       [7.15700567e-01, 2.74415702e-01, 9.88373347e-03],
       [7.18872964e-01, 2.71920532e-01, 9.20644403e-03],
       [6.85973644e-01, 2.95813888e-01, 1.82124171e-02],
       [8.11246514e-01, 1.88071311e-01, 6.82196580e-04],
       [6.77831411e-01, 3.00988764e-01, 2.11797915e-02],
       [6.80397153e-01, 2.99391955e-01, 2.02108882e-02],
       [8.21261466e-01, 1.78259656e-01, 4.78809845e-04],
       [4.90424156e-01, 3.36670518e-01, 1.72905415e-01],
       [7.63549685e-01, 2.33456641e-01, 2.99359299e-03],
       [7.15726912e-01, 2.74395078e-01, 9.87795368e-03],
       [6.86005950e-01, 2.95792788e-01, 1.82012729e-02],
       [7.57846713e-01, 2.38652125e-01, 3.50121735e-03],
       [6.91537738e-01, 2.92100072e-01, 1.63621418e-02],
       [3.17397118e-01, 2.74904191e-01, 4.07698661e-01],
       [6.69847131e-01, 3.05754930e-01, 2.43979469e-02],
       [6.79955840e-01, 2.99668789e-01, 2.03753002e-02],
       [7.57609725e-01, 2.38866478e-01, 3.52377351e-03],
       [2.81752974e-01, 2.55096376e-01, 4.63150650e-01],
       [7.82180309e-01, 2.16075778e-01, 1.74392504e-03],
       [5.90727925e-01, 3.36050421e-01, 7.32216462e-02],
       [8.04351151e-01, 1.94786713e-01, 8.62136600e-04],
       [5.98157048e-01, 3.34469795e-01, 6.73731267e-02],
       [7.34622777e-01, 2.59014070e-01, 6.36324659e-03],
       [7.17066348e-01, 2.73346096e-01, 9.58758686e-03],
       [6.98982179e-01, 2.86913693e-01, 1.41041176e-02],
       [5.86095452e-01, 3.36913854e-01, 7.69907013e-02],
       [5.86098075e-01, 3.36913437e-01, 7.69885629e-02],
       [6.60062134e-01, 3.11169416e-01, 2.87684221e-02],
       [7.07943201e-01, 2.80355245e-01, 1.17015680e-02],
       [5.99038959e-01, 3.34265888e-01, 6.66951314e-02],
       [7.69758224e-01, 2.27729052e-01, 2.51269643e-03],
       [6.92616165e-01, 2.91364014e-01, 1.60198100e-02],
       [7.42689252e-01, 2.52102435e-01, 5.20837400e-03],
       [5.24544954e-01, 3.40338051e-01, 1.35116935e-01],
       [6.55105233e-01, 3.13730657e-01, 3.11641134e-02],
       [4.04436529e-01, 3.13805133e-01, 2.81758368e-01],
       [6.91037893e-01, 2.92439520e-01, 1.65226012e-02],
       [6.56311870e-01, 3.13118517e-01, 3.05696409e-02],
       [6.01997316e-01, 3.33556265e-01, 6.44464493e-02],
       [5.54241478e-01, 3.40456784e-01, 1.05301775e-01],
       [6.46911383e-01, 3.17694783e-01, 3.53937857e-02],
       [7.15428650e-01, 2.74627745e-01, 9.94352344e-03],
       [6.68083847e-01, 3.06765556e-01, 2.51505654e-02],
       [6.22065365e-01, 3.27673107e-01, 5.02614789e-02],
       [5.10376930e-01, 3.39244097e-01, 1.50379002e-01],
       [4.75785702e-01, 3.34066153e-01, 1.90148145e-01],
       [6.36643589e-01, 3.22188497e-01, 4.11679484e-02],
       [6.27444685e-01, 3.25770378e-01, 4.67849411e-02],
       [6.84196532e-01, 2.96970069e-01, 1.88334864e-02],
       [4.09358889e-01, 3.15568954e-01, 2.75072187e-01],
       [3.16488892e-01, 2.74426222e-01, 4.09084976e-01],
       [5.75292706e-01, 3.38573694e-01, 8.61335173e-02],
       [6.70677066e-01, 3.05273950e-01, 2.40489878e-02],
       [6.70171559e-01, 3.05567324e-01, 2.42611505e-02],
       [7.82162011e-01, 2.16093093e-01, 1.74488977e-03],
       [5.76180816e-01, 3.38455588e-01, 8.53636339e-02],
       [6.43837392e-01, 3.19095343e-01, 3.70673090e-02],
       [7.23071218e-01, 2.68562406e-01, 8.36632587e-03],
       [5.90564907e-01, 3.36082399e-01, 7.33527020e-02],
       [8.22403848e-01, 1.77136809e-01, 4.59350704e-04],
       [5.77019095e-01, 3.38341087e-01, 8.46398771e-02],
       [5.68982065e-01, 3.39321107e-01, 9.16968733e-02],
       [6.17169023e-01, 3.29283625e-01, 5.35473190e-02],
       [3.91213685e-01, 3.08821678e-01, 2.99964637e-01],
       [7.39797235e-01, 2.54601806e-01, 5.60098933e-03],
       [6.20603442e-01, 3.28166008e-01, 5.12305200e-02],
       [4.71159905e-01, 3.33123833e-01, 1.95716307e-01],
       [6.38174772e-01, 3.21551621e-01, 4.02734987e-02]], dtype=float32)

In [50]:
penguins['species']

0         Adelie
1         Adelie
2         Adelie
3         Adelie
4         Adelie
         ...
328    Chinstrap
329    Chinstrap
330    Chinstrap
331    Chinstrap
332    Chinstrap
Name: species, Length: 333, dtype: object

In [51]:
penguins_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1], dtype=int8)